### ISSUE TITLE
プラグイン削除時に  MappingException がスローされる場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-api4#26]
`bin/console eccube:composer:remove ec-cube/Api` を実行した場合に、以下の MappingException がスローされる場合がある。
`composer install` を実行してから、再度 `eccube:composer:remove` を実行することで解消される

```
[68.7MiB/0.15s] Loading composer repositories with package information
[69.2MiB/0.15s] <warning>Warning: Accessing 127.0.0.1 over http which is an insecure protocol.</warning>
[69.2MiB/1.15s] Updating dependencies (including require-dev)
[466.2MiB/7.54s] Package operations: 0 installs, 0 updates, 11 removals
[466.2MiB/7.54s]   - Removing webonyx/graphql-php (v14.0.2)
[466.2MiB/7.57s]   - Removing trikoder/oauth2-bundle (v2.1.1)
[466.2MiB/7.59s]   - Removing symfony/psr-http-message-bridge (v1.2.0)
[466.2MiB/7.61s]   - Removing psr/http-factory (1.0.1)
[466.2MiB/7.63s]   - Removing php-http/message-factory (v1.0.2)
[466.2MiB/7.64s]   - Removing nyholm/psr7 (1.3.0)
[466.2MiB/7.66s]   - Removing league/oauth2-server (7.4.0)
[466.2MiB/7.68s]   - Removing league/event (2.2.0)
[466.2MiB/7.70s]   - Removing lcobucci/jwt (3.3.2)

In MappingException.php line 49:

  File mapping drivers must have a valid directory path, however the given path [/path/to/ec-cube/ven
  dor/trikoder/oauth2-bundle/Resources/config/doctrine/model] seems to be incorrect!


remove [--dev] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--no-update-with-dependencies] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] <packages> (<packages>)...


In ComposerApiService.php line 319:

  [Eccube\Exception\PluginException]


eccube:composer:remove [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <package>
```

**Comment by nanasess** [comment]
bundle 削除時に、 DoctrineOrmMappingsPass が削除されないのが原因っぽい。
以下のような流れで処理すれば解決できるかも

1. 物理テーブル名取得
2. DoctrineOrmMappingsPass 削除
3. 1 を削除

**Comment by okazy** [comment]
bundleのインストール時にもDoctrineの問題がありました。
https://github.com/EC-CUBE/ec-cube/pull/4462

こちらの時はDBの定義更新前にDBにアクセスしていて、キャッシュが作られてしまうというものだったかと思います。
関係あるかわかりませんが、参考になればと思います。

**Comment by nanasess** [comment]
bundle に依存した services.yaml がある場合、 bundle を読み込まないようにした時点で `There is no extension able to load the configuration for "<bundle name>"` のエラーになってしまう
https://github.com/EC-CUBE/ec-cube/issues/3936

**Comment by nanasess** [comment]
プラグインに bundle を依存させるのは難が多そうなので、 bundle を本体に依存させるかたちで問題無いか検証する

**Comment by nanasess** [comment]
以下 PR いただき、 MappingException が発生しないことを確認しました。
https://github.com/nanasess/ec-cube/pull/38

**Comment by nanasess** [comment]
管理画面からプラグインを削除しようとした際、以下のようなエラーが発生する場合がある。
画面上は、プラグイン削除のプログレスバーが表示され続けてしまう

```
Uncaught Warning:
  include(/Users/nanasess/git-repos/ec-cube/vendor/composer/../trikoder/oauth2-bundle/EventListener/ConvertExceptionToResponseListener.php):
  failed to open stream: No such file or directory
--> exception:
      class: Symfony\Component\Debug\Exception\ContextErrorException
      message: 'Warning: include(/Users/nanasess/git-repos/ec-cube/vendor/composer/../trikoder/oauth2-bundle/EventListener/ConvertExceptionToResponseListener.php): failed to open stream: No such file or directory'
      code: 0
      file: /Users/nanasess/git-repos/ec-cube/vendor/composer/ClassLoader.php
      line: 444
      trace: "#0 /Users/nanasess/git-repos/ec-cube/vendor/composer/ClassLoader.php(444): include()\n#1 /Users/nanasess/git-repos/ec-cube/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/Users/nanasess...')\n#2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/debug/DebugClassLoader.php(159): Composer\\Autoload\\ClassLoader->loadClass('Trikoder\\\\Bundle...')\n#3 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Trikoder\\\\Bundle...')\n#4 /Users/nanasess/git-repos/ec-cube/var/cache/dev/ContainerZf7nwbt/EccubeDevDebugProjectContainer.php(3657): spl_autoload_call('Trikoder\\\\Bundle...')\n#5 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(231): ContainerZf7nwbt\\EccubeDevDebugProjectContainer->ContainerZf7nwbt\\{closure}()\n#6 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(61): Symfony\\Component\\EventDispatcher\\EventDispatcher->sortListeners('kernel.exceptio...')\n#7 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(129): Symfony\\Component\\EventDispatcher\\EventDispatcher->getListeners('kernel.exceptio...')\n#8 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(259): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners('kernel.exceptio...')\n#9 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(137): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->preProcess('kernel.exceptio...')\n#10 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(227): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#11 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Symfony\\Component\\Debug\\Exception\\ContextErrorException), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#12 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#13 /Users/nanasess/git-repos/ec-cube/index.php(76): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}"
      previous: null
```

**Comment by nanasess** [comment]
以下のようなシステムエラーが発生し、E2Eテストが落ちる模様

```
システムエラーが発生しました。
--> - 'The file "/home/runner/work/ec-cube/ec-cube/app/Plugin/Horizon/Resource/config" does not exist.'
--> - /home/runner/work/ec-cube/ec-cube/vendor/symfony/config/FileLocator.php
--> - 44
--> - "#0 /home/runner/work/ec-cube/ec-cube/vendor/symfony/http-kernel/Config/FileLocator.php(52): Symfony\\Component\\Config\\FileLocator->locate('/home/runner/wo...', NULL, true)\n#1 /home/runner/work/ec-cube/ec-cube/vendor/symfony/config/Loader/FileLoader.php(110): Symfony\\Component\\HttpKernel\\Config\\FileLocator->locate('/home/runner/wo...', NULL, true)\n#2 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Loader/GlobFileLoader.php(31): Symfony\\Component\\Config\\Loader\\FileLoader->glob('/routes.{php,xm...', false, NULL)\n#3 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/RouteCollectionBuilder.php(373): Symfony\\Component\\Routing\\Loader\\GlobFileLoader->load('/home/runner/wo...', 'glob')\n#4 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/RouteCollectionBuilder.php(62): Symfony\\Component\\Routing\\RouteCollectionBuilder->load('/home/runner/wo...', 'glob')\n#5 /home/runner/work/ec-cube/ec-cube/src/Eccube/Kernel.php(192): Symfony\\Component\\Routing\\RouteCollectionBuilder->import('/home/runner/wo...', '/', 'glob')\n#6 /home/runner/work/ec-cube/ec-cube/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php(87): Eccube\\Kernel->configureRoutes(Object(Symfony\\Component\\Routing\\RouteCollectionBuilder))\n#7 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Loader/ObjectRouteLoader.php(65): Eccube\\Kernel->loadRoutes(Object(Symfony\\Component\\Routing\\Loader\\DependencyInjection\\ServiceRouterLoader))\n#8 /home/runner/work/ec-cube/ec-cube/vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\\Component\\Routing\\Loader\\ObjectRouteLoader->load('kernel:loadRout...', 'service')\n#9 /home/runner/work/ec-cube/ec-cube/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php(70): Symfony\\Component\\Config\\Loader\\DelegatingLoader->load('kernel:loadRout...', 'service')\n#10 /home/runner/work/ec-cube/ec-cube/vendor/symfony/framework-bundle/Routing/Router.php(56): Symfony\\Bundle\\FrameworkBundle\\Routing\\DelegatingLoader->load('kernel:loadRout...', 'service')\n#11 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Router.php(371): Symfony\\Bundle\\FrameworkBundle\\Routing\\Router->getRouteCollection()\n#12 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Router.php(289): Symfony\\Component\\Routing\\Router->getMatcherDumperInstance()\n#13 /home/runner/work/ec-cube/ec-cube/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php(43): Symfony\\Component\\Routing\\Router->Symfony\\Component\\Routing\\{closure}(Object(Symfony\\Component\\Config\\ResourceCheckerConfigCache))\n#14 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Router.php(302): Symfony\\Component\\Config\\ResourceCheckerConfigCacheFactory->cache('/home/runner/wo...', Object(Closure))\n#15 /home/runner/work/ec-cube/ec-cube/vendor/symfony/routing/Router.php(256): Symfony\\Component\\Routing\\Router->getMatcher()\n#16 /home/runner/work/ec-cube/ec-cube/vendor/symfony/http-kernel/EventListener/RouterListener.php(113): Symfony\\Component\\Routing\\Router->matchRequest(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 /home/runner/work/ec-cube/ec-cube/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Symfony\\Component\\HttpKernel\\EventListener\\RouterListener->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#18 /home/runner/work/ec-cube/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#19 /home/runner/work/ec-cube/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#20 /home/runner/work/ec-cube/ec-cube/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#21 /home/runner/work/ec-cube/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))\n#22 /home/runner/work/ec-cube/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#23 /home/runner/work/ec-cube/ec-cube/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#24 /home/runner/work/ec-cube/ec-cube/index.php(76): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#25 {main}"
```

**Comment by nanasess** [comment]
プラグイン有効化時に、以下のようなエラーが発生する場合がある

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning:
  require(/Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/getSwiftmailer_EmailSender_ListenerService.php):
  failed to open stream: No such file or directory" at
  /Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/EccubeDevDebugProjectContainer.php
  line 2248
--> exception:
      class: Symfony\Component\Debug\Exception\ContextErrorException
      message: 'Warning: require(/Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/getSwiftmailer_EmailSender_ListenerService.php): failed to open stream: No such file or directory'
      code: 0
      file: /Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/EccubeDevDebugProjectContainer.php
      line: 2248
      trace: "#0 /Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/EccubeDevDebugProjectContainer.php(2248): require()\n#1 /Users/nanasess/git-repos/ec-cube/var/cache/dev/Container8y6jiiw/EccubeDevDebugProjectContainer.php(3595): Container8y6jiiw\\EccubeDevDebugProjectContainer->load('getSwiftmailer_...')\n#2 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(231): Container8y6jiiw\\EccubeDevDebugProjectContainer->Container8y6jiiw\\{closure}()\n#3 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/EventDispatcher.php(61): Symfony\\Component\\EventDispatcher\\EventDispatcher->sortListeners('kernel.exceptio...')\n#4 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(129): Symfony\\Component\\EventDispatcher\\EventDispatcher->getListeners('kernel.exceptio...')\n#5 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(259): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->getListeners('kernel.exceptio...')\n#6 /Users/nanasess/git-repos/ec-cube/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(137): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->preProcess('kernel.exceptio...')\n#7 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(227): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent))\n#8 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel->handleException(Object(Twig\\Error\\RuntimeError), Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#9 /Users/nanasess/git-repos/ec-cube/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 /Users/nanasess/git-repos/ec-cube/index.php(76): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#11 {main}"
      previous: null
```
