### ISSUE TITLE
Webhooksを有効にするとエラーが発生する

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/eccube-api4#85]
Webhooksの登録をして商品などを編集すると発生

プロダクロモードで以下のエラーが発生

![image](https://user-images.githubusercontent.com/16895409/89365788-57c1f900-d710-11ea-8f76-92ac766874f3.png)

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Plugin\Api\Service\WebHookService::Plugin\Api\Service\{closure}() must be an instance of Nyholm\Psr7\Response, instance of GuzzleHttp\Psr7\Response given in /Users/hideki_okajima/temp/eccube-api/ec-cube-rc/app/Plugin/Api/Service/WebHookService.php:85 Stack trace: #0 [internal function]: Plugin\Api\Service\WebHookService->Plugin\Api\Service\{closure}(Object(GuzzleHttp\Psr7\Response), 0, Object(GuzzleHttp\Promise\Promise)) #1 /Users/hideki_okajima/temp/eccube-api/ec-cube-rc/vendor/guzzlehttp/promises/src/EachPromise.php(158): call_user_func(Object(Closure), Object(GuzzleHttp\Psr7\Response), 0, Object(GuzzleHttp\Promise\Promise)) #2 /Users/hideki_okajima/temp/eccube-api/ec-cube-rc/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Promise\EachPromise->GuzzleHttp\Promise\{closure}(Object(GuzzleHttp\Psr7\Response)) #3 /Users/hideki_okajima/temp/eccube-api/ec-cube-rc/vendor/guzzlehttp/promises/src/Promise.php(1 in /Users/hideki_okajima/temp/eccube-api/ec-cube-rc/app/Plugin/Api/Service/WebHookService.php on line 85
```

debugモードで実行すると

![image](https://user-images.githubusercontent.com/16895409/89366057-ff3f2b80-d710-11ea-8112-90d5b9a5abd6.png)

**Comment by okazy** [comment]
#86 で修正されました。
